### ISSUE TITLE
初始化db出现问题

### ISSUE THREAD

**Issue by raingolee** [Andrew-liu/flask_pure#2]
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from app import app
  File "/Users/raingolee/github/flask_pure/app/**init**.py", line 15, in <module>
    db = MongoEngine(app)  #实例化数据库
  File "/Users/raingolee/github/flask_pure/pure/lib/python3.5/site-packages/flask_mongoengine/**init**.py", line 33, in **init**
    self.init_app(app)
  File "/Users/raingolee/github/flask_pure/pure/lib/python3.5/site-packages/flask_mongoengine/**init**.py", line 66, in init_app
    self.connection = mongoengine.connect(**conn_settings)
  File "/Users/raingolee/github/flask_pure/pure/lib/python3.5/site-packages/mongoengine/connection.py", line 164, in connect
    return get_connection(alias)
  File "/Users/raingolee/github/flask_pure/pure/lib/python3.5/site-packages/mongoengine/connection.py", line 126, in get_connection
    raise ConnectionError("Cannot connect to database %s :\n%s" % (alias, e))
mongoengine.connection.ConnectionError: Cannot connect to database default :
[Errno 61] Connection refused

---

你好，是不是要启动Mongod 然后修改某个配置才能启动？

**Comment by Zhang21** [comment]
进不了/home 目录
